# Generated by Django 4.2.25 on 2025-10-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='\n\t\t<div class="about-me">\n              <h4>About me</h4>\n              <p>\n                I\'m an applied ecosystem ecologist passionate about bridging science and practice to tackle some of our world\'s biggest environmental challenges. \n                Currently, I lead strategy for a community-run conservation initiative in Nigeria, where I spearhead a sustainable agribusiness enterprise \n                that empowers local youth and women through job creation, economic and financial inclusion, and forest restoration.\n              </p>\n              <p>\n                Alongside my applied work, I am completing a PhD at Vrije Universiteit Brussel, where I study how large herbivores 🦓🦬🦒🦏🐘 shape \n                ecosystems stability and resilience. My goal is to provide actionable insights that inform environmental policy and climate resilience strategies.\n              </p>\n              <p>\n                My vision is to connect ecological science with development outcomes, from policy reform and nature recovery to inclusive growth and \n                the Sustainable Development Goals. I\'m always open to collaborations, partnerships, and opportunities in ecological research, \n                conservation, environmental consulting, and sustainable development.\n              </p>\n            </div>\n\t\t')),
                ('resume_url', models.URLField(default='https://drive.google.com/file/d/1CZ3dgW4PeTDTCc9me2sO2iOJQMM8C44J/view?usp=sharing')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
