# Generated by Django 4.2.25 on 2025-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_aboutmecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmecontent',
            name='content',
            field=models.TextField(default="I'm an applied ecosystem ecologist passionate about bridging science and practice to tackle some of our world's biggest environmental challenges.\n\tCurrently, I lead strategy for a community-run conservation initiative in Nigeria, where I spearhead a sustainable agribusiness enterprise that empowers\n\tlocal youth and women through job creation, economic and financial inclusion, and forest restoration.\n\n\tAlongside my applied work, I am completing a PhD at Vrije Universiteit Brussel, where I study how large herbivores 🦓🦬🦒🦏🐘 shape ecosystems stability\n\tand resilience. My goal is to provide actionable insights that inform environmental policy and climate resilience strategies.\n\n\tMy vision is to connect ecological science with development outcomes, from policy reform and nature recovery to inclusive growth and the Sustainable Development Goals.\n\tI'm always open to collaborations, partnerships, and opportunities in ecological research, conservation, environmental consulting, and sustainable development."),
        ),
    ]
